#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
export SOURCE_FILES="fastapi_extended_route tests"

set -x

${PREFIX}isort --check --diff --project=fastapi_extended_route $SOURCE_FILES
${PREFIX}black --check --diff $SOURCE_FILES
# ${PREFIX}mypy fastapi_extended_route
